### ISSUE TITLE
Inconsistent kerning in Gurmukhi

### ISSUE THREAD

**Issue by dscorbett** [notofonts/gurmukhi#2]
### Font
NotoSerifGurmukhi-Regular.otf

### Where the font came from, and when
Site: https://github.com/googlei18n/noto-fonts/blob/0a522f55b37b72f8b5013bd76fefddc74c9aeb4b/phaseIII_only/unhinted/otf/NotoSerifGurmukhi/NotoSerifGurmukhi-Regular.otf
Date: 2019-02-21

### Font version
Version 2.000

### Issue
The classes in the second subtable of the 'dist' lookup are missing lots of glyphs that should kern similarly to covered glyphs. The missing glyphs are precomposed with virama, addak, and nukta. For example, paguru is kerned before paguru but not before paprehalfguru.

### Character data
ਪਪ
U+0A2A GURMUKHI LETTER PA
U+0A2A GURMUKHI LETTER PA
ਪਪ੍
U+0A2A GURMUKHI LETTER PA
U+0A2A GURMUKHI LETTER PA
U+0A4D GURMUKHI SIGN VIRAMA

### Screenshot
kerned:
![ਪਪ](https://user-images.githubusercontent.com/1124347/53265843-32246980-36ad-11e9-8d3b-27bdf9e07859.png)
not kerned:
![ਪਪ੍](https://user-images.githubusercontent.com/1124347/53265845-32246980-36ad-11e9-8bed-9d67623c5047.png)
diff:
![ਪਪ ⊖ ਪਪ੍](https://user-images.githubusercontent.com/1124347/53266741-ae1fb100-36af-11e9-9745-b5a324e52fcc.png)

**Comment by simoncozens** [comment]
@JelleBosmaMT  said:

> Looking at the source file, it appears the designer...

Looking at the source file, that's you. :-) (If it was somebody else, we should get that fixed.)

>  For example, the ligatures with halant are fall-back glyphs, because normally explicit halants are not used in Panjabi text.

I wonder we even have the halant ligatures instead of just anchoring the halant. I'm going to try that; reducing the glyphset is always a win, and it'll also fix the kerning inconsistency.

**Comment by JelleBosmaMT** [comment]
> Op 16 feb. 2023, om 10:14 heeft Simon Cozens ***@***.***> het volgende geschreven:
> 
> 
> @JelleBosmaMT said:
> Looking at the source file, it appears the designer...
> Looking at the source file, that's you. :-) (If it was somebody else, we should get that fixed.)

I designed the Sans, not the Serif.

**Comment by simoncozens** [comment]
Oh, this issue is about the *serif*!

Still, I made some nice glyphset reductions anyway.

**Comment by JelleBosmaMT** [comment]
I think in the old Windows XP days the “guru” rendering expected a half feature.  For “gur2” I have no half feature in the sans, but the ligatures get used for haln, because they are there anyway. I don’t know if mark attachment is consistent with the ligatures, because there was no need to check and the virama doesn’t even need an anchor.
