### ISSUE TITLE
Nukta of LLA on wrong side?

### ISSUE THREAD

**Issue by simoncozens** [notofonts/gurmukhi#20]
We received a report that the nukta in the LLA glyph (0A33, lanuktaguru) should be attached to the bottom right, not the bottom left. Tiro Gurmukhi puts it on the bottom right, which I consider strong evidence that it should be, but most other fonts put it on the bottom left. Research required to determine the correct placement.

First step in research: Ask John. @tiroj, why did you put your nukta on the right?

**Comment by tiroj** [comment]
I recall the question initially arising during development of Nirmala UI for Microsoft. Initially, I had the nukta on the left, in keeping with its position on most other Gurmukhi letters, but I spotted it on the right in some of my reference materials, so queried this with Fiona, who thought yes, on the right, but referred the question to Professor Christopher Shackle and to Marina Chellini, the Punjabi curator at the BL, for confirmation.

**Comment by simoncozens** [comment]
Thank you!

**Comment by bgo-eiu** [comment]
For what it is worth, there is not really one "correct" side to put it on and in penned reference materials the nuktas can vary in direction because the placement had to do with where there was more space for it rather than a per-letter rule. LLA is wider towards the bottom than the other nukta characters, so it would make sense that it tends to be on the other side more often, and further when you consider in the context of Punjabi etymology, there is more freedom to choose where to put the Nukta that does not exist for the other nukta letters. The reason for this is that the other nukta letters are used in spellings of Persian loans, but ਲ਼ is a letter which only exists in native Punjabi words. So for example,

ਮਗ਼ਜ਼ੀ

is a Persian loan and if we allowed the nuktas to be added anywhere we could end up with nukta collisions. However, ਨਾਲ਼ occurs in words like

ਨਾਲ਼

and will never occur alongside another nukta letter including itself, so there is no chance of collision. Punjabi University renders the nukta underneath on their dicitonary site (see https://dic.learnpunjabi.org/default.aspx on the keyboard in the top ) and Sri Granth renders it to the left (see https://www.srigranth.org/servlet/gurbani.dictionary). So it is really just a stylistic choice where to put it.

You can see in some words why writers would want to switch which side it occurs on freely. For example, in most words where it occurs, like ਨਾਲ਼ it is towards the end, and it never occurs word-initially, so there is some logic in putting the nukta after. However, if we look at words like:

ਅਲ਼ਖ
ਵਲ਼ਗਣ

Placing the nukta on the right will make ਖ and ਗ look like ਖ਼ and ਗ਼ respectively. For this reason, I would actually recommend placing the nukta underneath ਲ or inside the gap like in ਜ਼ or ਸ਼ as this minimises the chance of ambiguity arising, and seems like a reasonable adaptation for typed text which could include any words as opposed to typeset print or handwriting where if the author were writing the words above, they would simply put the nukta on the left even if they put it on the right elsewhere in other contexts. (If you really wanted it to be on the side, maybe "smart" placement is possible which flips the directions for combinations followed by letters which could be ambiguous, but that might be going overboard depending on how strongly other users feel about this.)

**Comment by bgo-eiu** [comment]
I was mistaken: there is at least one loaned Perso-Arabic word/group of words derived from the same stem which has developed ਲ਼

Mnimal pairs:

ਹਲਕੇ  ہلکے
ਹਲ਼ਕ਼ੇ حࣇقے

Gulzar required to see the second on the right rendered correctly. ਕ਼ might be the only nukta letter Punjabis find more pedantic than ਲ਼ - Unicode does not have a precomposed character for it - but a dot collision is technically possible here. (I think of it as the "Iqbal letter" because most instances of it appear in writing the name Iqbal specifically. Correct Punjabi pronunciation of q / ਕ਼ / ق is exactly the same as k / ک / ਕ. However "Ikbal" or اکبال just "looks wrong" and ਕ਼ exists for the same reason q is used in the Latin script spellings of Muslim Punjabi names. I have a "q" in my name and I can't imagine writing it as "k" even though this is what it is, there is no perfectly logical explanation. Maybe could be said to be pseudo-honorific in function; capital letters are similarly pointless and Punjabi doesn't use them but names in English look "wrong" without them.)

**Comment by bgo-eiu** [comment]
![IMG_20221115_000021_023](https://user-images.githubusercontent.com/100172442/205195105-4dc490b6-7428-48c9-bc45-b2d68557ad87.jpg)
![IMG_20221115_000005_161](https://user-images.githubusercontent.com/100172442/205195131-2f19730a-eda8-42d2-bcb4-858c10feabb4.jpg)
![IMG_20221115_000336_560](https://user-images.githubusercontent.com/100172442/205195223-37000e2d-0323-4548-b807-729e0cec627c.jpg)


Some attestations of lalle pair bindi in print - in the middle underneath is actually the most common rendering in the books I have. The first two images are from Boota Singh Brar's Panjabi Bhasha: Sarot Te Saroop. He only includes the bindi when explaining phonetics. The third is from Punjabi Universitty's dictionary - you can see why it is printed underneath in this context as well, as placing it on the side would make the letter it belongs to ambiguous.

**Comment by simoncozens** [comment]
OK, so it looks like there is no "right" answer here and it is just a stylistic choice. Thank you!

**Comment by satnamsvirdi** [comment]
Adding a stylistic set would let people choose as per their needs. Your thoughts?

**Comment by simoncozens** [comment]
Sounds like a good idea.
