### ISSUE TITLE
'calt' is inconsistent about which clusters to separate

### ISSUE THREAD

**Issue by dscorbett** [notofonts/gurmukhi#22]
### Font
NotoSansGurmukhi-Regular.otf

### Where the font came from, and when
Site: https://github.com/notofonts/gurmukhi/releases/tag/NotoSansGurmukhi-v2.003
Date: 2022-09-07

### Font version
Version 2.003

### Issue
The 'calt' lookup slightly separates some clusters that would otherwise overlap, but the patterns are incomplete, so some similar character sequences produce overlapping glyphs.

### Character data
ਊੱਤੇ
U+0A0A GURMUKHI LETTER UU
U+0A71 GURMUKHI ADDAK
U+0A24 GURMUKHI LETTER TA
U+0A47 GURMUKHI VOWEL SIGN EE

ਉੱਤ਼ੇ
U+0A09 GURMUKHI LETTER U
U+0A71 GURMUKHI ADDAK
U+0A24 GURMUKHI LETTER TA
U+0A3C GURMUKHI SIGN NUKTA
U+0A47 GURMUKHI VOWEL SIGN EE

ਉੱਤੇੱ
U+0A09 GURMUKHI LETTER U
U+0A71 GURMUKHI ADDAK
U+0A24 GURMUKHI LETTER TA
U+0A47 GURMUKHI VOWEL SIGN EE
U+0A71 GURMUKHI ADDAK

### Screenshots
![ਊੱਤੇ](https://user-images.githubusercontent.com/1124347/188965884-2ba530d2-504f-4a47-b1d3-39542850e33e.png)
![ਉੱਤ਼ੇ](https://user-images.githubusercontent.com/1124347/188966076-8ba7cd18-df45-42e5-a94f-173a64523e88.png)
![ਉੱਤੇੱ](https://user-images.githubusercontent.com/1124347/188966324-8ebf1626-68b7-4e5e-bc75-d5672cd66fea.png)

**Comment by bgo-eiu** [comment]
These sequences do not occur in Punjabi as far as I know, nor can I think of a reason to use these spellings in transliterating words from other languages. ਊ and ੱੱ are nof supposed to occur together, the nukta on ਤ is used exceedingly rarely to represent ط in Perso-Arabic words which are unlikely to form that sequence, and two adhak syllables in a row are also not supposed to occur.

Maybe there are some uses cases for these I am not aware of, but this seems like intentional prioritisation of attested Punjabi spellings rather than an inconsistency.

**Comment by simoncozens** [comment]
Yes; I think, for once, I'm not going to fix this. The designers have obviously finessed the design with an additional glyph for some attested cases which touch, but I don't think it's worth adding more glyphs and more rules to finesse situations which are very unlikely to occur and which, to be honest, aren't *terribly* ugly when they do occur.

**Comment by satnamsvirdi** [comment]
As a native Punjabi speaker, I'd say that these spellings/clusters are not to found anywhere. They are not practical. But the one which is a common Punjabi word is similar to these clusters is "ਉੱਤੇ" (meaning: on or above).
